# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
    - 0.6
    - nightly
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("GeoMax"); Pkg.test("GeoMax"; coverage=true)';
    - julia -O3 -e 'include(joinpath(Pkg.dir("GeoMax"), "test/runtests.jl"))';
after_success:
  # push coverage results to Coveralls
  #- julia -e 'cd(Pkg.dir("GeoMax")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("GeoMax")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
